tipddy_survey_homepage:
    pattern:  /
    defaults: { _controller: TipddySurveyBundle:Default:index }

TipddySurveyBundle_survey:
    resource: "@TipddySurveyBundle/Resources/config/routing/survey.yml"
    prefix:   /survey