login:
    pattern: /
    defaults: { _controller: "TipddySecurityBundle:Default:login"}

login_check:
    pattern: /login_check

login_logout:
    pattern: /logout

TipddySecurityBundle_user:
    resource: "@TipddySecurityBundle/Resources/config/routing/user.yml"
    prefix:   /user

TipddySecurityBundle_role:
    resource: "@TipddySecurityBundle/Resources/config/routing/role.yml"
    prefix:   /role