TipddyBacnendBundle_dashboard:
    resource: "@TipddyBackendBundle/Resources/config/routing/dashboard.yml"
    prefix: /dashboard

TipddyBacnendBundle_comment:
    resource: "@TipddyBackendBundle/Resources/config/routing/comment.yml"
    prefix: /comment
